[package]
name = "deckbuilder"
version = "0.0.0"
authors = ["Esbysie <esbysie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
tokio = { version = "0.2", features = ["full"] }